
version: '3.1'

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./api:/app"
    ports:
      - "9000:3000"
    depends_on:
      - db

  db:
    image: mongo
    restart: always

    ports:
      - "27017:27017"
    volumes:
      - .data/db:/var/lib/mysql
